version: '3.4'
services:
  web:
    build: ./frontend
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env

  api:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    env_file:
      - .env
